@c *****************************************
@c *  Computer Algebra System SINGULAR     *
@c *****************************************

@multicolumn .45 .45
@item @ref{attrib} @tab @ref{attrib (plural)}
@item @ref{bareiss} @tab @code{---}
@item @ref{betti} @tab @ref{betti (plural)}
@item @ref{bigint} @tab @ref{bigint (plural)}
@item @ref{char} @tab @ref{char (plural)}
@item @ref{char_series} @tab @code{---}
@item @ref{charstr} @tab @ref{charstr (plural)}
@item @ref{close} @tab @ref{close (plural)}
@item @ref{ncols} @tab @ref{ncols (plural)}
@item @ref{cleardenom} @tab @ref{cleardenom (plural)}
@item @ref{size} @tab @ref{size (plural)}
@item @ref{def} @tab @ref{def (plural)}
@item @ref{deg} @tab @ref{deg (plural)}
@item @ref{degree} @tab @code{---}
@item @ref{defined} @tab @ref{defined (plural)}
@item @ref{det} @tab @ref{det (plural)}
@item @ref{dim} @tab @ref{dim (plural)}
@item @ref{dump} @tab @ref{dump (plural)}
@item @ref{gen} @tab @ref{gen (plural)}
@item @ref{execute} @tab @ref{execute (plural)}
@item @ref{ERROR} @tab @ref{ERROR (plural)}
@item @ref{factorize} @tab @code{---}
@item @ref{finduni} @tab @code{---}
@item @ref{freemodule} @tab @ref{freemodule (plural)}
@item @ref{facstd} @tab @code{---}
@item @ref{getdump} @tab @ref{getdump (plural)}
@item @ref{highcorner} @tab @code{---}
@item @ref{hilb} @tab @code{---}
@item @ref{homog} @tab @ref{homog (plural)}
@item @ref{ideal} @tab @ref{ideal (plural)}
@item @ref{impart} @tab @ref{impart (plural)}
@item @ref{indepSet} @tab @code{---}
@item @ref{int} @tab @ref{int (plural)}
@item @ref{interred} @tab @ref{interred (plural)}
@item @ref{intmat} @tab @ref{intmat (plural)}
@item @ref{intvec} @tab @ref{intvec (plural)}
@item @ref{rvar} @tab @ref{rvar (plural)}
@item @ref{jacob} @tab @ref{jacob (plural)}
@item @ref{janet} @tab @ref{janet (plural)}
@item @ref{kbase} @tab @ref{kbase (plural)}
@item @ref{ludecomp} @tab @code{---}
@item @ref{primefactors} @tab @ref{primefactors (plural)}
@item @ref{killattrib} @tab @ref{killattrib (plural)}
@item @ref{lead} @tab @ref{lead (plural)}
@item @ref{leadcoef} @tab @ref{leadcoef (plural)}
@item @ref{leadexp} @tab @ref{leadexp (plural)}
@item @ref{leadmonom} @tab @ref{leadmonom (plural)}
@item @ref{link} @tab @ref{link (plural)}
@item @ref{list} @tab @ref{list (plural)}
@item @ref{matrix} @tab @ref{matrix (plural)}
@item @ref{maxideal} @tab @ref{maxideal (plural)}
@item @ref{memory} @tab @ref{memory (plural)}
@item @ref{minbase} @tab @code{---}
@item @ref{minres} @tab @ref{minres (plural)}
@item @ref{module} @tab @ref{module (plural)}
@item @ref{monitor} @tab @ref{monitor (plural)}
@item @ref{monomial} @tab @ref{monomial (plural)}
@item @ref{mult} @tab @code{---}
@item @ref{mstd} @tab @code{---}
@item @ref{nameof} @tab @ref{nameof (plural)}
@item @ref{names} @tab @ref{names (plural)}
@item @ref{number} @tab @ref{number (plural)}
@item @ref{npars} @tab @ref{npars (plural)}
@item @ref{nvars} @tab @ref{nvars (plural)}
@item @ref{open} @tab @ref{open (plural)}
@item @ref{ord} @tab @ref{ord (plural)}
@item @ref{ordstr} @tab @ref{ordstr (plural)}
@item @ref{par} @tab @ref{par (plural)}
@item @ref{pardeg} @tab @ref{pardeg (plural)}
@item @ref{parstr} @tab @ref{parstr (plural)}
@item @ref{poly} @tab @ref{poly (plural)}
@item @ref{preimage} @tab @code{---}
@item @ref{prime} @tab @ref{prime (plural)}
@item @ref{print} @tab @ref{print (plural)}
@item @ref{proc} @tab @ref{proc (plural)}
@item @ref{prune} @tab @ref{prune (plural)}
@item @ref{qhweight} @tab @ref{qhweight (plural)}
@item @ref{rank} @tab @ref{rank (plural)}
@item @ref{read} @tab @ref{read (plural)}
@item @ref{regularity} @tab @code{---}
@item @ref{repart} @tab @ref{repart (plural)}
@item @ref{reservedName} @tab @ref{reservedName (plural)}
@item @ref{resolution} @tab @ref{resolution (plural)}
@item @ref{ringlist} @tab @ref{ringlist (plural)}
@item @ref{ring} @tab @ref{ring (plural)}
@item @ref{nrows} @tab @ref{nrows (plural)}
@item @ref{sba} @tab @ref{sba (plural)}
@item @ref{slimgb} @tab @ref{slimgb (plural)}
@item @ref{sortvec} @tab @ref{sortvec (plural)}
@item @ref{sqrfree} @tab @code{---}
@item @ref{std} @tab @ref{std (plural)}
@item @ref{string} @tab @ref{string (plural)}
@item @ref{syz} @tab @ref{syz (plural)}
@item @ref{envelope} @tab @ref{envelope (plural)}
@item @ref{opposite} @tab @ref{opposite (plural)}
@item @ref{twostd} @tab @ref{twostd (plural)}
@item @ref{trace} @tab @ref{trace (plural)}
@item @ref{transpose} @tab @ref{transpose (plural)}
@item @ref{typeof} @tab @ref{typeof (plural)}
@item @ref{univariate} @tab @ref{univariate (plural)}
@item @ref{variables} @tab @ref{variables (plural)}
@item @ref{vector} @tab @ref{vector (plural)}
@item @ref{vdim} @tab @ref{vdim (plural)}
@item @ref{var} @tab @ref{var (plural)}
@item @ref{varstr} @tab @ref{varstr (plural)}
@item @ref{weight} @tab @ref{weight (plural)}
@item @ref{load} @tab @ref{load (plural)}
@item @ref{convhull} @tab @ref{convhull (plural)}
@item @ref{waitfirst} @tab @ref{waitfirst (plural)}
@item @ref{waitall} @tab @ref{waitall (plural)}
@c ---------------------------------------------
@item @ref{div} @tab @ref{div (plural)}
@item @ref{mod} @tab @ref{mod (plural)}
@item @ref{and} @tab @ref{and (plural)}
@item @ref{or} @tab @ref{or (plural)}
@item @ref{attrib} @tab @ref{attrib (plural)}
@item @ref{betti} @tab @ref{betti (plural)}
@item @ref{bracket} @tab @ref{bracket (plural)}
@item @ref{chinrem} @tab @ref{chinrem (plural)}
@item @ref{coef} @tab @ref{coef (plural)}
@item @ref{coeffs} @tab @ref{coeffs (plural)}
@item @ref{contract} @tab @ref{contract (plural)}
@item @ref{deg} @tab @ref{deg (plural)}
@item @ref{delete} @tab @ref{delete (plural)}
@item @ref{diff} @tab @ref{diff (plural)}
@item @ref{dim} @tab @ref{dim (plural)}
@item @ref{division} @tab @ref{division (plural)}
@item @ref{eliminate} @tab @ref{eliminate (plural)}
@item @ref{exportto} @tab @ref{exportto (plural)}
@item @ref{extgcd} @tab @ref{extgcd (plural)}
@item @ref{factorize} @tab @code{---}
@item @ref{facstd} @tab @code{---}
@item @ref{farey} @tab @ref{farey (plural)}
@item @ref{fetch} @tab @ref{fetch (plural)}
@item @ref{fglm} @tab @code{---}
@item @ref{fglmquot} @tab @code{---}
@item @ref{find} @tab @ref{find (plural)}
@item @ref{frwalk} @tab @code{---}
@item @ref{gcd} @tab @ref{gcd (plural)}
@item @ref{hilb} @tab @code{---}
@item @ref{homog} @tab @ref{homog (plural)}
@item @ref{hres} @tab @code{---}
@item @ref{imap} @tab @ref{imap (plural)}
@item @ref{importfrom} @tab @ref{importfrom (plural)}
@item @ref{indepSet} @tab @code{---}
@item @ref{insert} @tab @ref{insert (plural)}
@item @ref{interpolation} @tab @code{---}
@item @ref{intersect} @tab @ref{intersect (plural)}
@item @ref{janet} @tab @ref{janet (plural)}
@item @ref{jet} @tab @ref{jet (plural)}
@item @ref{kbase} @tab @ref{kbase (plural)}
@item @ref{kernel} @tab @ref{kernel (plural)}
@item @ref{killattrib} @tab @ref{killattrib (plural)}
@item @ref{koszul} @tab @code{---}
@item @ref{kres} @tab @code{---}
@item @ref{lift} @tab @ref{lift (plural)}
@item @ref{liftstd} @tab @ref{liftstd (plural)}
@item @ref{load} @tab @ref{load (plural)}
@item @ref{lres} @tab @code{---}
@item @ref{modulo} @tab @ref{modulo (plural)}
@item @ref{monitor} @tab @ref{monitor (plural)}
@item @ref{mpresmat} @tab @code{---}
@item @ref{newstruct} @tab @ref{newstruct (plural)}
@item @ref{mres} @tab @ref{mres (plural)}
@item @ref{primefactors} @tab @ref{primefactors (plural)}
@item @ref{nc_algebra} @tab @code{---}
@item @ref{oppose} @tab @ref{oppose (plural)}
@item @ref{parstr} @tab @ref{parstr (plural)}
@item @ref{print} @tab @ref{print (plural)}
@item @ref{quotient} @tab @ref{quotient (plural)}
@item @ref{random} @tab @ref{random (plural)}
@item @ref{rank} @tab @ref{rank (plural)}
@item @ref{read} @tab @ref{read (plural)}
@item @ref{reduce} @tab @ref{reduce (plural)}
@item @ref{nres} @tab @ref{nres (plural)}
@item @ref{sqrfree} @tab @code{---}
@item @ref{status} @tab @ref{status (plural)}
@item @ref{simplify} @tab @ref{simplify (plural)}
@item @ref{sres} @tab @code{---}
@item @ref{sba} @tab @ref{sba (plural)}
@item @ref{std} @tab @ref{std (plural)}
@item @ref{varstr} @tab @ref{varstr (plural)}
@item @ref{waitfirst} @tab @ref{waitfirst (plural)}
@item @ref{waitall} @tab @ref{waitall (plural)}
@item @ref{wedge} @tab @code{---}
@c ---------------------------------------------
@item @ref{attrib} @tab @ref{attrib (plural)}
@item @ref{bareiss} @tab @code{---}
@item @ref{coeffs} @tab @ref{coeffs (plural)}
@item @ref{eliminate} @tab @code{---}
@item @ref{find} @tab @ref{find (plural)}
@item @ref{frwalk} @tab @code{---}
@item @ref{hilb} @tab @code{---}
@item @ref{homog} @tab @ref{homog (plural)}
@item @ref{insert} @tab @ref{insert (plural)}
@item @ref{intmat} @tab @ref{intmat (plural)}
@item @ref{jet} @tab @ref{jet (plural)}
@item @ref{koszul} @tab @code{---}
@item @ref{lift} @tab @ref{lift (plural)}
@item @ref{liftstd} @tab @ref{liftstd (plural)}
@item @ref{matrix} @tab @ref{matrix (plural)}
@item @ref{newstruct} @tab @ref{newstruct (plural)}
@item @ref{preimage} @tab @ref{preimage (plural)}
@item @ref{random} @tab @ref{random (plural)}
@item @ref{reduce} @tab @ref{reduce (plural)}
@item @ref{resultant} @tab @code{---}
@item @ref{ring} @tab @ref{ring (plural)}
@item @ref{sba} @tab @ref{sba (plural)}
@item @ref{status} @tab @ref{status (plural)}
@item @ref{std} @tab @code{---}
@item @ref{subst} @tab @ref{subst (plural)}
@item @ref{laguerre} @tab @code{---}
@item @ref{vandermonde} @tab @code{---}
@c ---------------------------------------------
@item @ref{breakpoint} @tab @ref{breakpoint (plural)}
@item @ref{coef} @tab @ref{coef (plural)}
@item @ref{division} @tab @ref{division (plural)}
@item @ref{dbprint} @tab @ref{dbprint (plural)}
@item @ref{ideal} @tab @ref{ideal (plural)}
@item @ref{intersect} @tab @ref{intersect (plural)}
@item @ref{intvec} @tab @ref{intvec (plural)}
@item @ref{jet} @tab @ref{jet (plural)}
@item @ref{LIB} @tab @ref{LIB (plural)}
@item @ref{list} @tab @ref{list (plural)}
@item @ref{luinverse} @tab @code{---}
@item @ref{lusolve} @tab @code{---}
@item @ref{minor} @tab @ref{minor (plural)}
@item @ref{module} @tab @ref{module (plural)}
@item @ref{names} @tab @ref{names (plural)}
@item @ref{option} @tab @ref{option (plural)}
@item @ref{reduce} @tab @ref{reduce (plural)}
@item @ref{reservedName} @tab @ref{reservedName (plural)}
@item @ref{string} @tab @ref{string (plural)}
@item @ref{subst} @tab @ref{subst (plural)}
@item @ref{system} @tab @ref{system (plural)}
@item @ref{test} @tab @ref{test (plural)}
@item @ref{write} @tab @ref{write (plural)}
@item @ref{status} @tab @ref{status (plural)}
@item @ref{simplex} @tab @code{---}
@item @ref{uressolve} @tab @code{---}
@item @ref{sba} @tab @ref{sba (plural)}
@item @ref{std} @tab @ref{std (plural)}
@item @ref{qrds} @tab @ref{qrds (plural)}
@item @ref{factmodd} @tab @ref{factmodd (plural)}
@c ---------------------------------------------
@end table
